Update copy-code-2-prod.yaml

diff --git a/.github/workflows/copy-code-2-prod.yaml b/.github/workflows/copy-code-2-prod.yaml
--- a/.github/workflows/copy-code-2-prod.yaml
+++ b/.github/workflows/copy-code-2-prod.yaml
@@ -83,11 +83,14 @@ jobs:
                     fi
                     ;;
                 "deploymentManifest")
-                # Similarly handle other cases
-                    ;;
-                *)
-                    echo "Invalid choice"
-                    ;;
+                echo "Contents of $(pwd)/non-prod/deploymentManifest/ directory:"
+                    ls -l $(pwd)/non-prod/deploymentManifest/
+                    if [ -d "$(pwd)/non-prod/deploymentManifest/" ]; then
+                        cp $(pwd)/non-prod/deploymentManifest/*.json $(pwd)/prod/deploymentManifest/ || (echo "Failed to copy JSON files." && exit 1)
+                        echo "Inputs updated for $choice"
+                    else
+                        echo "Directory $(pwd)/non-prod/deploymentManifest/ does not exist."
+                    fi
             esac
         shell: bash
 
